### ISSUE TITLE
misleading hover vs "highlighted" state

### ISSUE THREAD

**Issue by adnasa** [vutran/omnibar#13]
![kapture 2017-11-04 at 2 31 13](https://user-images.githubusercontent.com/462507/32401113-369e109e-c109-11e7-9082-64fea513df77.gif)

when we use the arrow keys to navigate up/down the list, our highlighting styles indicates clearly where we are within the list.

However, hovering with the mouse; we get the hovered item highlighted, while the previous item that we had navigated into retains its highlighted state.

I think this can be resolved partially/mitigated with #4,
but the underlying problem I've found is the scattered responsibility of setting the highlighted state. Here is what I found

- Omnibar: `hoveredIndex`
- ResultsItem: `highlight` => hover style appended

**Comment by vutran** [comment]
Now that we have a children render function (#14), we should be able to expose these in our new children function.

`isFocused` - currently selected item in the list (via arrow keys)

`isHighlighted` - mouse is currently hovered over the item

### Example API:

```jsx
<Omnibar>
    {({ item, isFocused, isHighlighted }) => {
        let backgroundColor = 'white';
        
        if (isFocused) {
            backgroundColor = 'lightgray';
        }

        if (isHighlighted) {
            backgroundColor = 'gray';
        }

        return <div style={{ backgroundColor }}>{item.title}</div>;
    }}
</Omnibar>
```

**Comment by vutran** [comment]
Can close this now :)
