### ISSUE TITLE
Misleading contribution guideline

### ISSUE THREAD

**Issue by adnasa** [vutran/omnibar#2]
According to the [Contribution guideline](https://github.com/vutran/omnibar#contributing) we just "run the app", but there is no such command for `yarn run` in `package.json`

Care to clarify this?

**Comment by vutran** [comment]
Looks like this was outdated. I have since moved the demo to an external repo [here](https://github.com/vutran/omnibar-www)

**Comment by vutran** [comment]
We should generate one from Insights > Community.

**Comment by vutran** [comment]
Resolved with this commit: e996b262614ea3694e763493af13315d179901f6
