### ISSUE TITLE
When I cloned the example and ran the problem, there was a problem

### ISSUE THREAD

**Issue by zhanghuan1203** [vutran/omnibar#27]
![deepinscrot-1539](https://user-images.githubusercontent.com/22954150/34664648-de11f9fa-f497-11e7-8f94-c3c487e41df0.png)

**Comment by vutran** [comment]
Hi, the current `master` branch is undergoing an API overhaul. I recommend installing the most recent version ([v1.1.0](https://github.com/vutran/omnibar/releases/tag/v1.1.0)) for now until a new version is released.
