### ISSUE TITLE
Styles for result items

### ISSUE THREAD

**Issue by AlexMarlo** [vutran/omnibar#33]
Hi
I am trying to apply styles for result items
But when i use resultStyle it applies style only for 'ul' tag but not to 'a' tags inside.
How i can solve it?

**Comment by vutran** [comment]
Hi @AlexMarlo, you should be able to do this with a [custom item renderer](https://github.com/vutran/omnibar/tree/v2.1.1#custom-renderers) providing your own layout for each result.
