### ISSUE TITLE
Change input style on focus 

### ISSUE THREAD

**Issue by AlexMarlo** [vutran/omnibar#34]
Github search change styles on focus.
What is the way to do this with omnibar?

**Comment by AlexMarlo** [comment]
May be we can do something like this ?

`
handleBlur = () => {
    if(this.props.onBlur) {
      this.props.onFocus.call();
    }
    setTimeout(() => this.setState({ displayResults: false }), BLUR_DELAY);
  };

  handleFocus = () => {
    if(this.props.onFocus) {
      this.props.onFocus.call();
    }
    this.setState({ displayResults: true });
  };
`

**Comment by vutran** [comment]
Merged in #35

**Comment by AlexMarlo** [comment]
Great, thanks
One more question, when i should expect this updates will be pushed to npm?

**Comment by vutran** [comment]
[`v2.2.0`](https://www.npmjs.com/package/omnibar/v/2.2.0) is now up.
