### ISSUE TITLE
`width` applies only on `<Input />`

### ISSUE THREAD

**Issue by adnasa** [vutran/omnibar#5]
Given the following code;
```js
          <Omnibar
            extensions={[SearchExtension]}
            rootStyle={{
              border: '1px solid #f00',
              position: 'relative',
              marginTop: '50px',
            }}
            width={300}
          />
```

we get this
![screen shot 2017-10-31 at 17 32 57](https://user-images.githubusercontent.com/462507/32236141-aa15a42e-be61-11e7-8d7f-58de74d53065.png)

This now brings me back to [my original concern](https://github.com/vutran/omnibar/issues/4#issuecomment-340820074) of `width` and `height`

**Comment by vutran** [comment]
Closing this issue as #15 is now merged.
